### PR TITLE
[1.x] Create, Put and delete

### LINKED ISSUE #2: Not possible to retrieve images
How the package is designed right now, is not possible to retrieve images URL from the Prestashop API.

Documentation to follow for an update:
[https://devdocs.prestashop.com/1.7/webservice/resources/images/#image_types](https://devdocs.prestashop.com/1.7/webservice/resources/images/#image_types)

### PR DESCRIPTION
**Pull request by pepijndik**
* ConfigException
* CouldNotConnectException
* CouldNotFindResource

### CODE REVIEW

**Comment by serwin35** [comment]
Nice :)) 

In my free time, I have to sit down and make a product record, including a photo and brand assignment

**Comment by pepijndik** [comment]
> 

I already have created the product resource I  am now working on the specific product prices. This is a other kind of filter

**Comment by serwin35** [comment]
> > 
> 
> I already have created the product resource I am now working on the specific product prices. This is a other kind of filter

wow great :) so what I can You help

**Comment by pepijndik** [comment]
> > > 
> > 
> > 
> > I already have created the product resource I am now working on the specific product prices. This is a other kind of filter
> 
> wow great :) so what I can You help

You could create the remaining resources, Check the dev branch :-D.
I have just finished the search for specific prices for a product

**Comment by pepijndik** [comment]
An Idea to merge?

**Comment by pepijndik** [comment]
@lucasgiovanny what do you think about my big refactor? :D

**Comment by lucasgiovanny** [comment]
@pepijndik Let's get this project back on track! I'm going to have a deep look at what you have done this week so we can prepare the next release. Sounds good? Get back to you soon.

**Comment by pepijndik** [comment]
> @pepijndik Let's get this project back on track! I'm going to have a deep look at what you have done this week so we can prepare the next release. Sounds good? Get back to you soon.

Sounds good!

**Comment by lucasgiovanny** [comment]
@pepijndik Let's merge this commit so we can have a stable starting point for version `1.x`. I think now we need to work on some tests and the new documentation, what do you think?

**Review by lucasgiovanny — APPROVED** [review]

**Comment by pepijndik** [comment]
A todo would be extending the tests. Currently te test URLs are pointing to my old testing prestashop

> @pepijndik Let's merge this commit so we can have a stable starting point for version `1.x`. I think now we need to work on some tests and the new documentation, what do you think?

i just wanted to mention that ;-D  lets base some tests on raw XML data so that there is not need for a real connection between prestashop

**Comment by lucasgiovanny** [comment]
Sounds good for the testing. I will start working on the documentation right now. 

By the way, I'm deleting `v2-dev` branch since is the same thing as `1.x` so we can focus the work there.

**Pull request merged**
